/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views;

import java.util.List;
import ViewModels.CuaHangViewModel;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import ServiceITF.CuaHangService;
import ServiceIplm.CuaHangServiceImpl;
import DomainModels.CuaHang;
import javax.swing.JOptionPane;

/**
 *
 * @author Kien
 */
public class CuaHangView extends javax.swing.JDialog {

    private List<CuaHangViewModel> list = new ArrayList<>();
    private List<CuaHang> lists = new ArrayList<>();
    private DefaultTableModel dtm = new DefaultTableModel();
    private CuaHangService ser = new CuaHangServiceImpl();

    public CuaHangView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        table1.setModel(dtm);
        dtm.setColumnIdentifiers(new Object[]{"id", "Ma", "Ten", "Dia Chi", "Thanh pho"});
        list = ser.getAll();
        showDaTa(list);

    }

    public void showDaTa(List<CuaHangViewModel> lst) {
        dtm.setRowCount(0);
        for (CuaHangViewModel ch : lst) {
            dtm.addRow(ch.toRowDaTa());
        }
    }

    public void showDaTaS(List<CuaHang> lsts) {
        dtm.setRowCount(0);
        for (CuaHang ch : lsts) {
            dtm.addRow(ch.toRowDaTa());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_MaCh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_TenCH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_DiaChi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_ThanhPho = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        bt_Sua = new javax.swing.JButton();
        bt_ADD = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText(" Cửa Hàng");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mã Cửa Hàng");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tên Cửa Hàng");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Địa Chỉ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Thành Phố");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        bt_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit.png"))); // NOI18N
        bt_Sua.setText("Sửa");
        bt_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SuaActionPerformed(evt);
            }
        });

        bt_ADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add.png"))); // NOI18N
        bt_ADD.setText("Thêm");
        bt_ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ADDActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.png"))); // NOI18N
        jButton4.setText("Tìm kiếm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_TenCH, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(47, 47, 47)
                                    .addComponent(txt_MaCh, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(bt_ADD)
                        .addGap(38, 38, 38)
                        .addComponent(bt_Sua)
                        .addGap(38, 38, 38)
                        .addComponent(jButton3)
                        .addGap(38, 38, 38)
                        .addComponent(jButton4)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_MaCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_TenCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_ThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Sua)
                    .addComponent(bt_ADD)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SuaActionPerformed
        String maCH = txt_MaCh.getText();
        CuaHang x = new CuaHang();
        x.setTenCh(txt_TenCH.getText());
        x.setDiaChi(txt_DiaChi.getText());
        x.setThanhPho(txt_ThanhPho.getText());

        try {
            if (txt_MaCh.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Mã Cửa Hàng không được để trống");
                return;
            }
            /*for (String c : service.getListMaCH()) {
                if (txtMaCH.getText().equals(c) == false) {
                    JOptionPane.showMessageDialog(this, "Mã Cửa Hàng không tồn tại");
                    return;
                }
            }*/
            if (checkMa() == false) {
                JOptionPane.showMessageDialog(this, "Mã Cửa Hàng không tồn tại");
                return;
            }
            if (txt_TenCH.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tên Cửa Hàng không được để trống");
                return;
            }
            if (txt_DiaChi.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Địa Chỉ không được để trống");
                return;
            }
            if (txt_ThanhPho.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Thành Phố không được để trống");
                return;
            }
            if (ser.sua(x, maCH)) {

                list = ser.getAll();
                showDaTa(list);
                JOptionPane.showMessageDialog(this, "Sửa Thành Công");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_bt_SuaActionPerformed
    public boolean checkMa() {
        String ma = txt_MaCh.getText();
        for (String c : ser.getListMaCH()) {
            if (txt_MaCh.getText().equals(c)) {
                return true;
            }
        }
        return false;
    }
    private void bt_ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ADDActionPerformed
        CuaHang x = new CuaHang();
        x.setMaCh(txt_MaCh.getText());
        x.setTenCh(txt_TenCH.getText());
        x.setDiaChi(txt_DiaChi.getText());
        x.setThanhPho(txt_ThanhPho.getText());
        try {
            if (txt_MaCh.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Mã Cửa Hàng không được để trống");
                return;
            }
            /*for (String c : service.getListMaCH()) {
                if (txtMaCH.getText().equals(c) == true) {
                    JOptionPane.showMessageDialog(this, "Mã Cửa Hàng đã được sử dụng");
                    return;
                }
            }*/
            if (checkMa()) {
                JOptionPane.showMessageDialog(this, "Mã Cửa Hàng đã được sử dụng");
                return;
            }
            if (txt_TenCH.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tên Cửa Hàng không được để trống");
                return;
            }
            if (txt_DiaChi.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Địa Chỉ không được để trống");
                return;
            }
            if (txt_ThanhPho.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Thành Phố không được để trống");
                return;
            }

            if (ser.insert(x)) {
                list = ser.getAll();
                JOptionPane.showMessageDialog(this, "Thêm Thành Công");
                showDaTa(list);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bt_ADDActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String maCH = txt_MaCh.getText();
        try {
            if (txt_MaCh.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Mã Cửa Hàng không được để trống");
                return;
            }
            /*for (String c : service.getListMaCH()) {
                if (txtMaCH.getText().equals(c) == false) {
                    JOptionPane.showMessageDialog(this, "Mã Cửa Hàng không tồn tại");
                    return;
                }
            }*/
            if (checkMa() == false) {
                JOptionPane.showMessageDialog(this, "Mã Cửa Hàng không tồn tại");
                return;
            }
            if (ser.xoa(maCH)) {
                list = ser.getAll();
                JOptionPane.showMessageDialog(this, "Xóa Thành Công");
                showDaTa(list);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        int row = table1.getSelectedRow();
        txt_MaCh.setText(table1.getValueAt(row, 1).toString());
        txt_TenCH.setText(table1.getValueAt(row, 2).toString());
        txt_DiaChi.setText(table1.getValueAt(row, 3).toString());
        txt_ThanhPho.setText(table1.getValueAt(row, 4).toString());
    }//GEN-LAST:event_table1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuaHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuaHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuaHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuaHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CuaHangView dialog = new CuaHangView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ADD;
    private javax.swing.JButton bt_Sua;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table1;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_MaCh;
    private javax.swing.JTextField txt_TenCH;
    private javax.swing.JTextField txt_ThanhPho;
    // End of variables declaration//GEN-END:variables
}
