/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
import DomainModels.DienThoai;
import ServiceITF.DienThoaiService;
import ServiceIplm.DienThoaiServiceImpl;

/**
 *
 * @author Kien
 */
public class FromDienThoai extends javax.swing.JFrame {

    private DefaultTableModel dtm = new DefaultTableModel();
    private DefaultComboBoxModel cbbmode = new DefaultComboBoxModel();
    private DefaultComboBoxModel cbbmodes = new DefaultComboBoxModel();
    private DefaultComboBoxModel cbbmodess = new DefaultComboBoxModel();
    private DefaultComboBoxModel cbbmodesss = new DefaultComboBoxModel();
    private DefaultComboBoxModel cbbmodessss = new DefaultComboBoxModel();
    private List<DienThoai> list = new ArrayList<>();
    private List<String> lstString = new ArrayList<>();
    private List<String> lstStrings = new ArrayList<>();
    private List<String> lstStringss = new ArrayList<>();
    private List<String> lstStringsss = new ArrayList<>();
    private List<String> lstStringssss = new ArrayList<>();
    private DienThoaiService servive = new DienThoaiServiceImpl();
    public FromDienThoai() {
        initComponents();
        setLocationRelativeTo(null);
        dtm = (DefaultTableModel) table1.getModel();
        dtm.setColumnIdentifiers(new Object[]{"Ma dt", "Ma cua hang", "Ten", "Loai", "Hang", "Mau", "Ngay san xuat", "Ngay xuat ban", "So luong", "Trang thai", "Gia", "Ram", "He dieu hanh", "Chip xl", "CPU"});
        loadDaTaCbbLoai();
        loadDaTaCbbhang();
        loadDaTaCbbHDH();
        loadDaTaCbbCPU();
        loadDaTaCbbCXL();
        list = servive.getAll();
        showDaTa(list);
    }

    public void showDaTa(List<DienThoai> lst) {
        dtm.setRowCount(0);
        for (DienThoai dt : lst) {
            dtm.addRow(dt.toRowData());
        }
    }
    public void fillTable(){
        
    }

    public void loadDaTaCbbLoai() {
        cbb_Loai.setModel(cbbmode);
        lstString.add("Cam ung");
        lstString.add("Khong cam ung");
        for (String s : lstString) {
            cbbmode.addElement(s);
        }
    }

    public void loadDaTaCbbhang() {
        cbb_Hang.setModel(cbbmodes);
        lstStrings.add("Iphone");
        lstStrings.add("SamSung");
        lstStrings.add("NoKia");
        lstStrings.add("Oppo");
        for (String sts : lstStrings) {
            cbbmodes.addElement(sts);
        }
    }

    public void loadDaTaCbbHDH() {
        cbb_HeDieuHanh.setModel(cbbmodess);
        lstStringss.add("IOS");
        lstStringss.add("Android");
        for (String stss : lstStringss) {
            cbbmodess.addElement(stss);
        }
    }

    public void loadDaTaCbbCXL() {
        cbb_ChipXuLy.setModel(cbbmodesss);
        lstStringsss.add("Apple A16 Bionic");
        lstStringsss.add("MediaTek Dimensity 9000 Plus");
        lstStringsss.add("Qualcomm Snapdragon 8 Gen 1");
        lstStringsss.add("Samsung Exynos 2200");
        for (String stsss : lstStringsss) {
            cbbmodesss.addElement(stsss);
        }
    }

    public void loadDaTaCbbCPU() {
        cbb_Cpu.setModel(cbbmodessss);
        lstStringssss.add("A15");
        lstStringssss.add("A16");
        lstStringssss.add("A13");
        lstStringssss.add("A11");
        for (String stssss : lstStringssss) {
            cbbmodessss.addElement(stssss);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_MaDt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_MaCh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Ten = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbb_Loai = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbb_Hang = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_Mau = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_Nsx = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Nxb = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_SoLuong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_TrangThai = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_Gia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_Ram = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbb_HeDieuHanh = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbb_ChipXuLy = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cbb_Cpu = new javax.swing.JComboBox<>();
        bt_Add = new javax.swing.JButton();
        bt_Update = new javax.swing.JButton();
        bt_Delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ma dt");

        jLabel2.setText("Ma Cua Hang");

        jLabel3.setText("Ten");

        jLabel4.setText("Loai");

        jLabel5.setText("Hang");

        jLabel6.setText("Mau");

        jLabel7.setText("Ngay san xuat");

        jLabel8.setText("Ngay xuat Ban");

        jLabel9.setText("So luong");

        jLabel10.setText("Trang thai");

        jLabel11.setText("Gia");

        jLabel12.setText("Ram");

        jLabel13.setText("He Dieu hanh");

        jLabel14.setText("Chip su ly");

        jLabel15.setText("CPU");

        bt_Add.setText("Them");
        bt_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AddActionPerformed(evt);
            }
        });

        bt_Update.setText("Sua");
        bt_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_UpdateActionPerformed(evt);
            }
        });

        bt_Delete.setText("Xoa");
        bt_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_DeleteActionPerformed(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_MaDt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_MaCh, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbb_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(bt_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_Nsx, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cbb_Hang, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txt_Mau, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_Nxb, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_TrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel13))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(bt_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_Ram, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbb_ChipXuLy, 0, 127, Short.MAX_VALUE)
                        .addComponent(cbb_HeDieuHanh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cbb_Cpu, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_MaDt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbb_Hang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cbb_HeDieuHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_MaCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_Mau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txt_TrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cbb_ChipXuLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_Nsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cbb_Cpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cbb_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Nxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txt_Ram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Add)
                    .addComponent(bt_Update)
                    .addComponent(bt_Delete))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AddActionPerformed
       DienThoai dt = new DienThoai();
       dt.setMaDt(txt_MaDt.getText());
       dt.setMaCh(txt_MaCh.getText());
       dt.setTen(txt_Ten.getText());
       dt.setLoai(cbb_Loai.getSelectedItem().toString());
       dt.setHang(cbb_Hang.getSelectedItem().toString());
       dt.setMau(txt_Mau.getText());
       dt.setNgaySanXuat(txt_Nsx.getText());
       dt.setNgayXuatBan(txt_Nxb.getText());
       dt.setSoLuong(txt_SoLuong.getText());
       dt.setTrangThai(txt_TrangThai.getText());
       dt.setGia(txt_Gia.getText());
       dt.setRam(txt_Ram.getText());
       dt.setHeDieuHanh(cbb_HeDieuHanh.getSelectedItem().toString());
       dt.setChipSuLy(cbb_ChipXuLy.getSelectedItem().toString());
       dt.setCpu(cbb_Cpu.getSelectedItem().toString());
       list = servive.insertDienThoai(list, dt);
       showDaTa(list);
    }//GEN-LAST:event_bt_AddActionPerformed

    private void bt_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_UpdateActionPerformed
       DienThoai dt = new DienThoai();
       dt.setMaDt(txt_MaDt.getText());
       dt.setMaCh(txt_MaCh.getText());
       dt.setTen(txt_Ten.getText());
       dt.setLoai(cbb_Loai.getSelectedItem().toString());
       dt.setHang(cbb_Hang.getSelectedItem().toString());
       dt.setMau(txt_Mau.getText());
       dt.setNgaySanXuat(txt_Nsx.getText());
       dt.setNgayXuatBan(txt_Nxb.getText());
       dt.setSoLuong(txt_SoLuong.getText());
       dt.setTrangThai(txt_TrangThai.getText());
       dt.setGia(txt_Gia.getText());
       dt.setRam(txt_Ram.getText());
       dt.setHeDieuHanh(cbb_HeDieuHanh.getSelectedItem().toString());
       dt.setChipSuLy(cbb_ChipXuLy.getSelectedItem().toString());
       dt.setCpu(cbb_Cpu.getSelectedItem().toString());
       list = servive.updateDienThoai(list, dt);
       showDaTa(list);
    }//GEN-LAST:event_bt_UpdateActionPerformed

    private void bt_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_DeleteActionPerformed
        String ma = txt_MaDt.getText();
        list = servive.deleteDienThoai(list, ma);
        showDaTa(list);
    }//GEN-LAST:event_bt_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromDienThoai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromDienThoai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromDienThoai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromDienThoai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromDienThoai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Add;
    private javax.swing.JButton bt_Delete;
    private javax.swing.JButton bt_Update;
    private javax.swing.JComboBox<String> cbb_ChipXuLy;
    private javax.swing.JComboBox<String> cbb_Cpu;
    private javax.swing.JComboBox<String> cbb_Hang;
    private javax.swing.JComboBox<String> cbb_HeDieuHanh;
    private javax.swing.JComboBox<String> cbb_Loai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table1;
    private javax.swing.JTextField txt_Gia;
    private javax.swing.JTextField txt_MaCh;
    private javax.swing.JTextField txt_MaDt;
    private javax.swing.JTextField txt_Mau;
    private javax.swing.JTextField txt_Nsx;
    private javax.swing.JTextField txt_Nxb;
    private javax.swing.JTextField txt_Ram;
    private javax.swing.JTextField txt_SoLuong;
    private javax.swing.JTextField txt_Ten;
    private javax.swing.JTextField txt_TrangThai;
    // End of variables declaration//GEN-END:variables
}
