/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DomainModels.KichCo;
import ServiceIplm.KichCoService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class KichCoViews extends javax.swing.JFrame {

    
    DefaultTableModel dtm = new DefaultTableModel();
    private KichCoService listKC = new KichCoService();
    
    /**
     * Creates new form KichCo
     */
    public KichCoViews() {
        initComponents();
        
        dtm = (DefaultTableModel) jTableKichCo.getModel();
        dtm.setRowCount(0);
        loadData();

        String headers[] = {"Mã Kích Cỡ", "Tên Kích Cỡ"};
        dtm.setColumnIdentifiers(headers);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    void loadData() {
        List<KichCo> kc = listKC.select();
        for (KichCo kichCo : kc) {
            dtm.addRow(new Object[]{
                kichCo.getMaKC(),
                kichCo.getTenKC()
            });
        }
    }

    void clear() {
        txtMaKichCo.setText("");
        txtTenKichCo.setText("");
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaKichCo = new javax.swing.JTextField();
        txtTenKichCo = new javax.swing.JTextField();
        btnThemKC = new javax.swing.JButton();
        btnSuaKC = new javax.swing.JButton();
        btnXoaKC = new javax.swing.JButton();
        btnTimKiemKC = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableKichCo = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã Kích Cỡ:");

        jLabel2.setText("Tên Kích Cỡ:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("KÍCH CỠ SẢN PHẨM");

        btnThemKC.setText("Thêm");
        btnThemKC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKCActionPerformed(evt);
            }
        });

        btnSuaKC.setText("Sửa");
        btnSuaKC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaKCActionPerformed(evt);
            }
        });

        btnXoaKC.setText("Xoá");
        btnXoaKC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKCActionPerformed(evt);
            }
        });

        btnTimKiemKC.setText("Tìm Kiếm");
        btnTimKiemKC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemKCActionPerformed(evt);
            }
        });

        jTableKichCo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableKichCo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableKichCoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableKichCo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnThemKC, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(btnSuaKC, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(btnXoaKC)
                                        .addGap(21, 21, 21)
                                        .addComponent(btnTimKiemKC))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTenKichCo, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                            .addComponent(txtMaKichCo))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaKichCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenKichCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemKC)
                    .addComponent(btnSuaKC)
                    .addComponent(btnXoaKC)
                    .addComponent(btnTimKiemKC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemKCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKCActionPerformed
        // TODO add your handling code here:
        String ma = txtMaKichCo.getText();
        String ten = txtTenKichCo.getText();
        try {
            listKC.them(ma, ten);
            dtm.setRowCount(0);
            loadData();
            clear();
            return;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemKCActionPerformed

    private void btnSuaKCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaKCActionPerformed
        // TODO add your handling code here:
        int row = jTableKichCo.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chon thông tin cần sửa");
            return;
        } else {
            String ma = txtMaKichCo.getText();
            String ten = txtTenKichCo.getText();
         try {
            listKC.sua(ma, ten);
            dtm.setRowCount(0);
            loadData();
            clear();
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_btnSuaKCActionPerformed

    private void btnXoaKCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKCActionPerformed
        // TODO add your handling code here:
        int row = jTableKichCo.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn thông tin cần xoá");
            return;
        } else {
            String ma = txtMaKichCo.getText();
            try {
                listKC.xoa(ma);
                dtm.setRowCount(0);
                loadData();
                clear();
                return;
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnXoaKCActionPerformed

    private void btnTimKiemKCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemKCActionPerformed
        // TODO add your handling code here:
        String ma = JOptionPane.showInputDialog(null, "Vui lòng nhập mã Kích Cỡ");
        try {
            List<KichCo> kc = listKC.getOne(ma);
            dtm.setRowCount(0);
            for (KichCo kichCo : kc) {
                dtm.addRow(new Object[]{
                    kichCo.getMaKC(),
                    kichCo.getTenKC()
                });
            }
            clear();
            return;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTimKiemKCActionPerformed

    private void jTableKichCoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKichCoMouseClicked
        // TODO add your handling code here:
        int row = jTableKichCo.getSelectedRow();
        KichCo list = listKC.fina().get(row);
        txtMaKichCo.setText(list.getMaKC());
        txtTenKichCo.setText(list.getTenKC());
    }//GEN-LAST:event_jTableKichCoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KichCoViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KichCoViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KichCoViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KichCoViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KichCoViews().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaKC;
    private javax.swing.JButton btnThemKC;
    private javax.swing.JButton btnTimKiemKC;
    private javax.swing.JButton btnXoaKC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableKichCo;
    private javax.swing.JTextField txtMaKichCo;
    private javax.swing.JTextField txtTenKichCo;
    // End of variables declaration//GEN-END:variables
}
